### ISSUE TITLE
Dependency conflict with upgrade to laravel 11

### ISSUE THREAD

**Issue by boonstoppel** [clickbar/laravel-magellan#80]
Problem 1
    - illuminate/console[v9.0.0-beta.1, ..., 9.x-dev] require symfony/process ^6.0 -> found symfony/process[v6.0.0-BETA1, ..., 6.4.x-dev] but it conflicts with your root composer.json require (^7.0).
    - illuminate/console[v10.0.0, ..., 10.x-dev] require symfony/process ^6.2 -> found symfony/process[v6.2.0-BETA1, ..., 6.4.x-dev] but it conflicts with your root composer.json require (^7.0).
    - clickbar/laravel-magellan 1.5.0 requires illuminate/console ^9.0|^10.0 -> satisfiable by illuminate/console[v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev].
    - Root composer.json requires clickbar/laravel-magellan ^1.5 -> satisfiable by clickbar/laravel-magellan[1.5.0].

**Comment by saibotk** [comment]
Yes we did not yet release the new version but you can just override the repository in composer to use the main branch

**Comment by boonstoppel** [comment]
sorry, I don't understand. How do you suggest I resolve this conflict?
