### ISSUE TITLE
update-postgis-columns inserts code at top of the file

### ISSUE THREAD

**Issue by brausepulver** [clickbar/laravel-magellan#85]
Running the command on a model with geometry columns in the database but no $postgisColumns inserts code at the top of the file outside of the class:

```php
<?php

    protected array $postgisColumns = [
        'geog' => [
            'type' => 'geography',
            'srid' => 4326,
        ],
    ];

    use HasPostgisColumns;
```

This only happens when $postgisColumns is not present on the model. When $postgisColumns is present the column definitions are inserted correctly.

In other cases the command prompts to change code that is the exact same as the proposed code.

**Comment by saibotk** [comment]
Oh good catch sorry for the inconvenience, and thanks for filing the issue 👍

**Comment by saibotk** [comment]
Theoretically the array should be added below any traits or the line with `class YourModel extends Model ....`.

Can you show me the beginning of your model file? With the same formatting etc?

**Comment by saibotk** [comment]
This feature will be removed in 2.x anyway.

So we will close this issue for now :) 

Thanks for your report!
