### ISSUE TITLE
Numeric Expression doesn't work in custom query

### ISSUE THREAD

**Issue by ybert** [clickbar/laravel-magellan#98]
I would like to execute this query :
```php
        $lineString = MagellanBaseExpression::geometry('ST_LineFromEncodedPolyline', [$polyline]);
        $query = PassPG::query()
            ->stSelect(ST::length(
                MagellanBaseExpression::geometry('ST_Substring', [
                    GeoParam::wrap($lineString),
                    0,
                    MagellanBaseExpression::numeric('ST_LineLocatePoint', [
                        GeoParam::wrap($lineString),
                        GeoParam::wrap('location'),
                    ])
                ]),
                true
            ), 'location_in_meter')
            ->get();
```

But I get this error :
```Object of class Clickbar\\Magellan\\Database\\MagellanExpressions\\MagellanNumericExpression could not be converted to string```

**Comment by saibotk** [comment]
Sry for the late reply :)

This is currently not a bug, you need to wrap the numeric expression as a GeoParam too.

Hope this helps :) 

We are currently revisiting this API design and will probably improve the DX in the future too :)
